---
name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  yamllint:
    name: 'yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '.github/workflows'
          yamllint_strict: false
          yamllint_config_filepath: '.yamllint'
