---
name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  yamllint:
    name: 'yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: '.github/workflows'
          yamllint_strict: false
          yamllint_config_filepath: '.yamllint'
  actionlint:
    runs-on: ubuntu-latest
    container:
      image: rhysd/actionlint:1.6.8
      options: --user root
    steps:
      - uses: actions/checkout@v2
      - name: run-actionlint
        run: |
          mkdir .git
          actionlint -color
