---
name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  workflow-ci:
    uses: vergesense/gha-workflow-ci/.github/workflows/workflow_ci.yml@main
    with:
      actionlint-ignore: -ignore 'property ".+" is not defined in object type'
