---
name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-workflow:
    name: color is cool
    runs-on: ubuntu-latest
    steps:
      - id: assign
        uses: actions/github-script@v5
        with:
          script: |
            core.setOutput('color', 'pink');
      - id: call
        run: |
          echo "color is ${{ steps.assign.outputs.color }}"
